title: Stephan Griesel
subtitle: "Personal Blog"
description: "Stephan's Blog"
author: Stephan Griesel
language: en
timezone: UTC

url: https://blog.stephangriesel.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:stephangriesel/static-hexo-site.git

highlight:
  enable: true
  line_number: false